sonar.projectKey=katagaki_SakuraRSS
sonar.organization=katagaki

sonar.exclusions=SakuraRSS/Views/Shared/Readability/Readability.js
sonar.cpd.exclusions=SakuraRSS/Views/Shared/Readability/Readability.js
sonar.coverage.exclusions=SakuraRSS/Views/Shared/Readability/Readability.js
